HomeWork: Part1, Exercise1
java8-course/streams pull request #2
Opened 2016-09-27 21:04 UTC by ASaunin

2016-09-29 09:23 UTC, senia-psm requested changes

2016-09-29 09:23 UTC, senia-psm commented on src/test/java/part1/exercise/StreamsExercise1.java
> +    private static final Predicate<String> employerWorkedForEpam = e -> e.equals("epam");
Use `"epam"::equals` instead

2016-09-29 09:23 UTC, senia-psm commented on src/test/java/part1/exercise/StreamsExercise1.java
> +    public static void generateEmployeeList() {
Use static import instead

2016-09-29 09:23 UTC, senia-psm commented on src/test/java/part1/exercise/StreamsExercise1.java
> +                .filter(j -> employerWorkedForEpam.test(getEmployer.apply(j)))
I guess `j.getEmployer().equals("epam")` is more readable.

2016-09-29 09:23 UTC, senia-psm commented on src/test/java/part1/exercise/StreamsExercise2.java
> +    private Map<String, Person> getGreatestExperiencePerEmployer(List<Employee> employees) {
You should prefer Person with 10 single year records over Person with a single 5 years record.

2016-09-29 09:23 UTC, senia-psm commented on src/test/java/part1/exercise/StreamsExercise2.java
> +        employersStuffLists.keySet()
Use asserts instead.

2016-09-29 12:15 UTC, ASaunin commented on src/test/java/part1/exercise/StreamsExercise1.java
> +                .filter(j -> employerWorkedForEpam.test(getEmployer.apply(j)))
It's really less readable, but we already have employerWorkedForEpam function for compearing. 
I just wanted to use it

2016-09-29 22:21 UTC, ASaunin commented on src/test/java/part1/exercise/StreamsExercise2.java
> +        employersStuffLists.keySet()
Expected lists are too long, may I don't do this?
I implemented assertation in CollectorsExercise1 - it's rather short

2016-09-30 07:16 UTC, senia-psm commented on src/test/java/part1/exercise/StreamsExercise2.java
> +        employersStuffLists.keySet()
As you like. Note that you can check not only equality, but also some other properties using `allMatch`, `nonMatch` etc.

2016-09-30 07:22 UTC, senia-psm requested changes

2016-09-30 07:22 UTC, senia-psm commented on src/test/java/part2/exercise/CollectorsExercise1.java
> +                    EnumSet.of(Characteristics.CONCURRENT));
Incorrect. `CONCURRENT` means that you can add elements into single accumulator from multiple threads. Actually you can't add elements into `HashMap` from multiple threads.

2016-09-30 11:43 UTC, ASaunin commented on src/test/java/part2/exercise/CollectorsExercise1.java
> +                    EnumSet.of(Characteristics.CONCURRENT));
Can you explain one more time, how to set characteristics properly?

2016-09-30 11:53 UTC, senia-psm commented on src/test/java/part2/exercise/CollectorsExercise1.java
> +                    EnumSet.of(Characteristics.CONCURRENT));
Use empty set. There should be no properties.

2017-08-31 22:01 UTC, closed without merging